- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    enabled: yes
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes

- block:
  - name: enable required repositories
    rhsm_repository: name={{ required_repos | join(',') }}
    register: enabled_repos

  - name: Disable all repositories except required_repos
    rhsm_repository:
      name: "{{ enabled_repos.repositories |
       map(attribute='id') |
       difference(required_repos) |
       join(',' ) }}"
      state: disabled
  when:
    - enable_rh_repos is defined
    - enable_rh_repos

- name: Install collectd and required plugins
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd

- name: Install iostat
  package:
    name: sysstat
    state: present

- name: Create collectd python plugin directory
  file:
    path: /usr/lib64/collectd/plugins/python
    state: directory
    owner: root
    group: root

- name: Create collectd bash plugin directory
  file:
    path: /usr/lib64/collectd/plugins/bash
    state: directory
    owner: root
    group: root

- name: Download collectd-iostat plugin
  get_url:
    url: https://raw.githubusercontent.com/deniszh/collectd-iostat-python/master/collectd_iostat_python.py
    dest: /usr/lib64/collectd/plugins/python/collectd_iostat_python.py
    mode: 0755

- name: Download collectd-iostat type database
  get_url:
    url: https://raw.githubusercontent.com/deniszh/collectd-iostat-python/master/iostat_types.db
    dest: /usr/share/collectd/iostat_types.db

- name: Copy collectd config file
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
    owner: root
    group: root
    mode: 0644

- name: copy collectd network bandwith usage plugin
  copy:
    src: nic_throughput.sh
    dest: /usr/lib64/collectd/plugins/bash/nic_throughput.sh
    mode: 0755

- name: Copy collectd config file
  template:
    src: network-bandwidth-usage.conf.j2
    dest: /etc/collectd.d/network-bandwidth-usage.conf
    owner: root
    group: root
    mode: 0755

- name: Unfortunately set SELinux to permissive to make collectd-iostat work
  selinux:
    policy: targeted
    state: permissive

- name: install collectd-gluster prerequisites
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python2-psutil
    - collectd-virt

- name: download collectd-gluster
  unarchive:
    src: https://github.com/gluster/gluster-collectd/archive/master.zip
    dest: /tmp
    remote_src: yes

- name: create directory for collectd-gluster
  file:
    path: /usr/lib64/collectd/gluster-collectd
    state: directory
    mode: 0755

- name: copy collectd-gluster files
  shell: cp -a /tmp/gluster-collectd-master/{{ item.0 }} {{ item.1 }}
  with_together:
    - [src/*, conf/gluster.conf.template, types/types.db.gluster]
    - [/usr/lib64/collectd/gluster-collectd/, /etc/collectd.d/gluster.conf, /usr/share/collectd/]

- name: hack to fix collectd service not starting
  lineinfile:
    path: /usr/lib64/collectd/gluster-collectd/gluster_plugins/brick_stats.py
    regexp: '(^\s*)self.CONFIG'
    line: '\1socket.gethostname()'
    backrefs: yes

- name: (re)start and enable collectd
  service:
    name: collectd
    state: restarted
    enabled: yes


#- name: Copy collectd config file
#  template:
#    src: network-bandwidth-usage.conf.j2
#    dest: /etc/collectd.d/network-bandwidth-usage.conf
#    owner: root
#    group: root
#    mode: 0644
